services:
  app:
    image: robiningelbrecht/strava-statistics:v3.8.4
    container_name: statistics-for-strava
    restart: unless-stopped
    volumes:
      - ./config/config.yaml:/var/www/config/app/config.yaml:ro
      - strava-statistics.build:/var/www/build
      - strava-statistics.db:/var/www/storage/database
      - strava-statistics.files:/var/www/storage/files
    environment:
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - STRAVA_REFRESH_TOKEN=${STRAVA_REFRESH_TOKEN}
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    networks:
      - proxy  
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.strava.loadbalancer.server.port=8080"
      - "traefik.http.routers.strava.rule=Host(`strava.darksaber.fyi`)"
      - "traefik.http.routers.strava.entrypoints=https"
      - "traefik.http.routers.strava.tls=true"
      - "traefik.http.routers.strava.middlewares=default-acl@docker,pocket-id@docker"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true

volumes:
  strava-statistics.build:
  strava-statistics.db:
  strava-statistics.files:
