services:
  papra:
    image: ghcr.io/papra-hq/papra:25.12.0-rootless
    container_name: papra
    networks:
      - proxy
    restart: unless-stopped
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - APP_BASE_URL=https://documents.darksaber.fyi
    volumes:
      - papra.data:/app/app-data
    user: 1000:1000

volumes:
  papra.data:

networks:
  proxy:
    external: true