services:
  papra:
    image: ghcr.io/papra-hq/papra:25.12.0-rootless
    container_name: papra
    networks:
      - proxy
    restart: unless-stopped
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_PROVIDERS_CUSTOMS=${AUTH_PROVIDERS_CUSTOMS}
      - AUTH_PROVIDERS_EMAIL_IS_ENABLED=false
      - APP_BASE_URL=https://documents.darksaber.fyi
    volumes:
      - papra.data:/app/app-data
    user: 1000:1000
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.papra.loadbalancer.server.port=1221"
      - "traefik.http.routers.papra.rule=Host(`documents.darksaber.fyi`)"
      - "traefik.http.routers.papra.entrypoints=https"
      - "traefik.http.routers.papra.tls=true"
      - "traefik.docker.network=proxy"

volumes:
  papra.data:

networks:
  proxy:
    external: true