x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  # This image will mount the volume and then simply execute chown on the parent folder for the UID/GID specified.
  chown:
    image: "alpine"
    entrypoint: ["/bin/ash", "-c"]
    command:
      - |
        chown -R 99:100 /postgres
    volumes:
      - "postgres.etc:/postgres/etc"
      - "postgres.var:/postgres/var"
      - "postgres.backup:/postgres/backup"

  postgres:
    depends_on:
      chown:
        condition: service_completed_successfully
    image: "11notes/postgres:18"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # make a full and compressed database backup each day at 03:00
      POSTGRES_BACKUP_SCHEDULE: "25 23 * * *"
      # only keep the last five backups
      POSTGRES_BACKUP_RETENTION: 5
    ports:
      - "5432:5432/tcp"
    user: "99:100"
    networks:
      proxy:
    volumes:
      - "postgres.etc:/postgres/etc"
      - "postgres.var:/postgres/var"
      - "postgres.backup:/postgres/backup"
    tmpfs:
      # needed for read-only
      - "/postgres/run:uid=99,gid=100"
      - "/postgres/log:uid=99,gid=100"
    restart: "always"

volumes:
  postgres.etc:
  postgres.var:
  postgres.backup:
    driver_opts:
      type: "nfs"
      o: "addr=srv-unraid.local.darksaber.fyi,hard,timeo=50,retrans=5,relatime,rsize=1048576,wsize=1048576,nfsvers=4"
      device: ":/mnt/user/containers/11notes-test2/postgres/backup"

networks:
  proxy: