---
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.31.0
    container_name: audiobookshelf
    networks:
      - proxy
    ports:
      - 8282:80
    environment:
      - TZ=Europe/Berlin
    volumes:
      - audiobookshelf.config:/config
      - audiobookshelf.metadata:/metadata
      - /mnt/user/data-ssd/media/audiobooks:/audiobooks
      - /mnt/user/data-ssd/media/podcasts:/podcasts
      - /mnt/user/data-ssd/media/radioplays:/radioplays
    labels:
      # Traefik
      - "traefik.enable=true"
      - "kop.bind.ip=srv-unraid.local.darksaber.fyi"
      - "traefik.http.services.abs.loadbalancer.server.port=8282"
      - "traefik.http.routers.abs.rule=Host(`abs.darksaber.fyi`)"
      - "traefik.http.routers.abs.entrypoints=https"
      - "traefik.http.routers.abs.tls=true"
    restart: always

networks:
  proxy:
    external: true

volumes:
  audiobookshelf.config:
  audiobookshelf.metadata:
